### ISSUE TITLE
Game menu crashes

### ISSUE THREAD

**Issue by Starbuck5** [Starbuck5/Kessler-Syndrome#41]
Steps to reproduce:
-start the font scrambling
-pause and quit to menu
-press the obscured play button

Steps to fix:
-create a way in the font class to end scrambling
-implement that whenever someone goes from the game through pause to the main menu

**Comment by icemoon97** [comment]
I fixed the font scrambling issue but the game still crashes if you collect anything or hit an asteroid and then try to quit to menu and play again. Probably and issue with the object list or saving or something?
